name: build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: go version
      - uses: actions/checkout@v2
      - run: make mod-download
      - name: Build
        run: make build
      - name: Test
        run: make test
