name: build
on: [push, pull_request]
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download modules to local cache
        run: make mod-download

      - name: Build
        run: make build

      - name: Test
        run: make test
